#!/bin/bash
#SBATCH --partition=bgfsqdr
#SBATCH --job-name=NAB_SM
#SBATCH --time=2:00:00
#SBATCH --output=Output/matlabHTM.%j
#SBATCH --ntasks=1
#SBATCH --cores-per-socket=8
#SBATCH --mem=16384

module load apps/matlab/r2020b

date

matlab -nodisplay -nosplash -r "run('runNAB($1,$2,false,true)')"

date


