#!/bin/bash
#SBATCH --partition=bgfsqdr
#SBATCH --job-name=VIX_SM_3
#SBATCH --time=00:15:00
#SBATCH --output=Output/matlabHTMRM.%j
#SBATCH --ntasks=8
#SBATCH --mem=8192

module load apps/matlab/r2019a

date

matlab -nodisplay -nosplash -r "run('runNAB($1,$2,false,true,true,false)')"

date


